apiVersion: apps/v1
kind: Deployment
metadata:
  name: logtest-deployment
  labels:
    app: logtest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logtest
  template:
    metadata:
      labels:
        app: logtest
    spec:
      containers:
        - name: logtest
          image: dykkim01/logtest
          ports:
          - containerPort: 8080
          env:
          - name: SPRING_PROFILE_ACTIVE
            value: "kubernetes"